// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A backlink (note that links to another note).
 */
export type BacklinkDto = { from_note_id: bigint, from_note_path: string, from_note_title: string | null, };
