// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Card-specific configuration.
 */
export type CardConfig = { 
/**
 * Property to use as cover image (expects a URL or path to an image).
 */
cover_property: string | null, 
/**
 * Fields to display on each card.
 */
display_fields: Array<string>, 
/**
 * Number of columns in the grid (0 = auto).
 */
columns: number, 
/**
 * Property to toggle on card click (e.g., "read" for reading lists).
 */
toggle_property: string | null, 
/**
 * Position of toggle button on card.
 */
toggle_position: string | null, 
/**
 * Dim card when toggle property is true.
 */
dim_when_true: boolean | null, };
