// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from converting frontmatter to DB properties.
 */
export type ConvertFrontmatterResponse = { 
/**
 * The new content without frontmatter (to replace in editor).
 */
content: string, 
/**
 * Number of properties converted to DB.
 */
properties_converted: number, 
/**
 * Tags that were converted to inline format.
 */
tags_converted: Array<string>, };
