// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HabitType } from "./HabitType";

/**
 * Request to create a new habit.
 */
export type CreateHabitRequest = { name: string, description: string | null, habit_type: HabitType, unit: string | null, color: string | null, target_value: number | null, };
