// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create a new schedule block.
 */
export type CreateScheduleBlockRequest = { note_id: bigint | null, date: string, start_time: string, end_time: string, label: string | null, color: string | null, context: string | null, };
