// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of creating a daily note.
 */
export type DailyNoteResult = { 
/**
 * The note ID.
 */
id: bigint, 
/**
 * The note path.
 */
path: string, 
/**
 * The note title.
 */
title: string | null, 
/**
 * Whether the note was newly created (true) or already existed (false).
 */
created: boolean, };
