// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to delete a property key from all notes.
 */
export type DeletePropertyKeyRequest = { 
/**
 * The property key to delete.
 */
key: string, };
