// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of resolving an embed.
 */
export type EmbedContent = { 
/**
 * The note ID if found in database.
 */
note_id: bigint | null, 
/**
 * The resolved path to the note or image.
 */
path: string, 
/**
 * The markdown content to embed (for notes).
 */
content: string | null, 
/**
 * Whether this is an image embed.
 */
is_image: boolean, 
/**
 * Asset URL for images (using Tauri asset protocol).
 */
asset_url: string | null, 
/**
 * Error message if resolution failed.
 */
error: string | null, };
