// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress of embedding rebuild operation.
 */
export type EmbeddingProgress = { 
/**
 * Current number of notes processed.
 */
processed: bigint, 
/**
 * Total number of notes to process.
 */
total: bigint, 
/**
 * Whether the operation is complete.
 */
complete: boolean, 
/**
 * Error message if any.
 */
error: string | null, };
