// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Settings for embedding generation via LM Studio.
 */
export type EmbeddingSettings = { 
/**
 * Whether semantic search is enabled.
 */
enabled: boolean, 
/**
 * LM Studio API endpoint URL (e.g., "http://localhost:1234/v1").
 */
endpoint_url: string, 
/**
 * Model name for embeddings (e.g., "nomic-ai/nomic-embed-text-v1.5-GGUF").
 */
model: string, 
/**
 * Embedding vector dimensions (e.g., 768 for nomic-embed-text).
 */
dimensions: number, 
/**
 * Number of texts to process in a single batch.
 */
batch_size: number, };
