// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of the embedding service connection.
 */
export type EmbeddingStatus = { 
/**
 * Whether the embedding service is reachable.
 */
connected: boolean, 
/**
 * Error message if not connected.
 */
error: string | null, 
/**
 * Number of notes with embeddings.
 */
indexed_count: bigint, 
/**
 * Total number of notes.
 */
total_count: bigint, };
