// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to execute a query embed (YAML string).
 */
export type ExecuteQueryEmbedRequest = { 
/**
 * The YAML content of the query block.
 */
yaml_content: string, };
