// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How to match multiple filter conditions.
 */
export type FilterMatchMode = "All" | "Any";
