// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A key-value property for a folder (inherited by notes in that folder tree).
 */
export type FolderPropertyDto = { id: bigint, folder_path: string, key: string, value: string | null, 
/**
 * Type hint: "text", "date", "number", "boolean", "list"
 */
property_type: string | null, };
