// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A node in the folder tree.
 */
export type FolderNode = { name: string, path: string, is_dir: boolean, children: Array<FolderNode>, };
