// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single habit entry (log).
 */
export type HabitEntryDto = { id: bigint, habit_id: bigint, 
/**
 * Date as YYYY-MM-DD string.
 */
date: string, 
/**
 * Optional time as HH:MM:SS string (for multiple entries per day).
 */
time: string | null, 
/**
 * Value as string (interpreted based on habit_type).
 */
value: string, 
/**
 * Optional notes for this entry.
 */
notes: string | null, };
