// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HabitDateRange } from "./HabitDateRange";
import type { HabitTableOrientation } from "./HabitTableOrientation";
import type { HabitViewType } from "./HabitViewType";

/**
 * Query for habit tracker embed.
 */
export type HabitTrackerQuery = { 
/**
 * Habit names or IDs to include (empty = all non-archived).
 */
habits: Array<string>, 
/**
 * View type.
 */
view: HabitViewType, 
/**
 * Table orientation (only applies to table view).
 */
orientation: HabitTableOrientation, 
/**
 * Date range preset.
 */
date_range: HabitDateRange, 
/**
 * Reference date for computing date ranges (YYYY-MM-DD). Defaults to today.
 * Useful for templates where you want to center the view on a specific date.
 */
date: string | null, 
/**
 * Custom start date (YYYY-MM-DD) when date_range is Custom.
 */
start_date: string | null, 
/**
 * Custom end date (YYYY-MM-DD) when date_range is Custom.
 */
end_date: string | null, 
/**
 * Whether cells are editable in the embed.
 */
editable: boolean, 
/**
 * Whether to show summary row (totals, streaks).
 */
show_summary: boolean, };
