// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HabitType } from "./HabitType";

/**
 * A habit definition.
 */
export type HabitDto = { id: bigint, name: string, description: string | null, habit_type: HabitType, 
/**
 * Unit for number habits (e.g., "minutes", "glasses", "km").
 */
unit: string | null, 
/**
 * Color for visual display (hex or named color).
 */
color: string | null, 
/**
 * Target value for number habits (e.g., 8 glasses).
 */
target_value: number | null, 
/**
 * Whether the habit is archived (soft deleted).
 */
archived: boolean, 
/**
 * Sort order for display.
 */
sort_order: number, };
