// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HabitDto } from "./HabitDto";
import type { HabitEntryDto } from "./HabitEntryDto";

/**
 * Habit with its entries for a date range.
 */
export type HabitWithEntries = { habit: HabitDto, 
/**
 * Entries organized by date (YYYY-MM-DD -> entries).
 */
entries_by_date: Array<[string, Array<HabitEntryDto>]>, };
