// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HabitTrackerQuery } from "./HabitTrackerQuery";
import type { HabitWithEntries } from "./HabitWithEntries";

/**
 * Response for habit tracker embed.
 */
export type HabitTrackerResponse = { 
/**
 * The parsed query configuration.
 */
query: HabitTrackerQuery, 
/**
 * Habits with their entries.
 */
habits: Array<HabitWithEntries>, 
/**
 * Actual date range start (YYYY-MM-DD).
 */
date_range_start: string, 
/**
 * Actual date range end (YYYY-MM-DD).
 */
date_range_end: string, 
/**
 * Error message if query failed.
 */
error: string | null, };
