// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Date range preset for habit tracker.
 */
export type HabitDateRange = "single_day" | "last7_days" | "last30_days" | "this_week" | "this_month" | "custom";
