// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a heading in a note (for section autocomplete).
 */
export type HeadingInfo = { 
/**
 * Heading level (1-6).
 */
level: number, 
/**
 * The heading text as displayed.
 */
text: string, 
/**
 * URL-safe slug for linking (e.g., "my-section").
 */
slug: string, };
