// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for hybrid search.
 */
export type HybridSearchOptions = { 
/**
 * Whether to use semantic search (requires embeddings enabled).
 */
use_semantic: boolean, 
/**
 * Weight for FTS results in combined score (0.0 - 1.0).
 */
fts_weight: number, 
/**
 * Maximum results to return.
 */
limit: number, };
