// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchType } from "./MatchType";

/**
 * A hybrid search result combining FTS5 and vector search.
 */
export type HybridSearchResult = { note_id: bigint, path: string, title: string | null, snippet: string | null, 
/**
 * BM25 score from FTS5 search (if matched).
 */
fts_score: number | null, 
/**
 * Cosine similarity from vector search (if matched).
 */
vector_score: number | null, 
/**
 * Combined score using Reciprocal Rank Fusion.
 */
combined_score: number, 
/**
 * How this result was matched.
 */
match_type: MatchType, };
