// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to import an Obsidian vault.
 */
export type ImportVaultRequest = { 
/**
 * Path to the source Obsidian vault.
 */
source_path: string, 
/**
 * Optional subfolder within the target vault to import into.
 */
target_subfolder: string | null, };
