// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of vault import.
 */
export type ImportResult = { 
/**
 * Number of notes imported.
 */
notes_imported: bigint, 
/**
 * Number of files copied (includes non-markdown assets).
 */
files_copied: bigint, 
/**
 * Number of properties imported from frontmatter.
 */
properties_imported: bigint, 
/**
 * Number of tags imported (from frontmatter).
 */
tags_imported: bigint, 
/**
 * Duration of import in milliseconds.
 */
duration_ms: bigint, 
/**
 * Any warnings or skipped files.
 */
warnings: Array<string>, };
