// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress update during vault import.
 */
export type ImportProgress = { 
/**
 * Current file being processed.
 */
current_file: string, 
/**
 * Number of files processed so far.
 */
files_processed: bigint, 
/**
 * Total number of files to process.
 */
total_files: bigint, 
/**
 * Number of properties imported.
 */
properties_imported: bigint, 
/**
 * Number of tags imported.
 */
tags_imported: bigint, };
