// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for index:complete event.
 */
export type IndexCompletePayload = { notes_indexed: bigint, duration_ms: bigint, };
