// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Interactive filter configuration.
 */
export type InteractiveFilter = { 
/**
 * Property key to filter on.
 */
key: string, 
/**
 * Filter UI style ("chips", "buttons", or "dropdown").
 */
style: string, 
/**
 * Show "All" option to clear filter.
 */
show_all: boolean, 
/**
 * Allow selecting multiple values.
 */
multi_select: boolean, 
/**
 * Optional display label for the filter.
 */
label: string | null, };
