// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kanban-specific configuration.
 */
export type KanbanConfig = { 
/**
 * Property to group cards into columns (e.g., "priority", "status", "context").
 */
group_by: string, 
/**
 * Fields to display on each card.
 */
card_fields: Array<string>, 
/**
 * Whether to show cards without a value in an "Uncategorized" column.
 */
show_uncategorized: boolean, };
