// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to log a habit entry.
 */
export type LogHabitEntryRequest = { habit_id: bigint, 
/**
 * Date as YYYY-MM-DD string.
 */
date: string, 
/**
 * Optional time as HH:MM:SS string.
 */
time: string | null, 
/**
 * Value to log.
 */
value: string, 
/**
 * Optional notes.
 */
notes: string | null, };
