// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a result was matched in hybrid search.
 */
export type MatchType = "Keyword" | "Semantic" | "Both";
