// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to merge two property keys (rename source to target, merging if target exists).
 */
export type MergePropertyKeysRequest = { 
/**
 * The property key to merge from (will be deleted).
 */
source_key: string, 
/**
 * The property key to merge into (will keep all values).
 */
target_key: string, };
