// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full note content for editing.
 */
export type NoteContent = { id: bigint, path: string, content: string, };
