// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A note that uses a specific property, including the value.
 */
export type NoteWithPropertyValue = { 
/**
 * The note ID.
 */
note_id: bigint, 
/**
 * The note path.
 */
path: string, 
/**
 * The note title (if any).
 */
title: string | null, 
/**
 * The property value in this note.
 */
value: string | null, };
