// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Minimal note info for lists/search results.
 */
export type NoteListItem = { id: bigint, path: string, title: string | null, pinned: boolean, };
