// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A note as exposed to the frontend.
 */
export type NoteDto = { id: bigint, path: string, title: string | null, created_at: string | null, updated_at: string | null, pinned: boolean, };
