// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for notes:updated event.
 */
export type NotesUpdatedPayload = { note_ids: Array<bigint>, };
