// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteListItem } from "./NoteListItem";
import type { ScheduleBlockDto } from "./ScheduleBlockDto";

/**
 * A note with its association type to a date.
 */
export type NoteForDate = { note: NoteListItem, 
/**
 * "scheduled", "journal", or "created"
 */
source: string, 
/**
 * If source is "scheduled", the schedule block info
 */
schedule_block: ScheduleBlockDto | null, };
