// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A property with inheritance information.
 */
export type PropertyWithInheritance = { id: bigint, key: string, value: string | null, property_type: string | null, sort_order: number | null, 
/**
 * True if this property is inherited from a folder (not directly set on the note).
 */
inherited: boolean, 
/**
 * The folder path this property is inherited from (if inherited).
 */
inherited_from: string | null, };
