// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a property key used in the vault.
 */
export type PropertyKeyInfo = { 
/**
 * The property key name.
 */
key: string, 
/**
 * Number of notes using this property.
 */
usage_count: bigint, 
/**
 * Sample values for this property (up to 10).
 */
sample_values: Array<string>, 
/**
 * Most common property type for this key (text, date, number, boolean, list).
 */
property_type: string | null, };
