// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A key-value property for a note (stored in SQLite, not frontmatter).
 */
export type PropertyDto = { id: bigint, note_id: bigint, key: string, value: string | null, 
/**
 * Type hint: "text", "date", "number", "boolean", "list"
 */
property_type: string | null, sort_order: number | null, };
