// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operator for property filters.
 */
export type PropertyOperator = "Exists" | "NotExists" | "Equals" | "NotEquals" | "Contains" | "StartsWith" | "EndsWith";
