// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a property value used in the vault.
 */
export type PropertyValueInfo = { 
/**
 * The property value.
 */
value: string, 
/**
 * Number of notes using this value.
 */
usage_count: bigint, };
