// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertyOperator } from "./PropertyOperator";

/**
 * A single property filter condition.
 */
export type PropertyFilter = { 
/**
 * The property key to filter on.
 */
key: string, 
/**
 * The comparison operator.
 */
operator: PropertyOperator, 
/**
 * The value to compare against (not used for Exists/NotExists).
 */
value: string | null, };
