// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for bulk property operations.
 */
export type PropertyOperationResult = { 
/**
 * Number of properties affected.
 */
affected_count: bigint, 
/**
 * Number of notes affected.
 */
notes_affected: bigint, };
