// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What type of results to return.
 */
export type QueryResultType = "Tasks" | "Notes" | "Both";
