// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryEmbed } from "./QueryEmbed";
import type { QueryResultItem } from "./QueryResultItem";
import type { TabResult } from "./TabResult";

/**
 * Response from executing a query embed.
 */
export type QueryEmbedResponse = { 
/**
 * The parsed query configuration.
 */
query: QueryEmbed, 
/**
 * The results matching the query (for single-query mode).
 */
results: Array<QueryResultItem>, 
/**
 * Total count of matching items (for single-query mode).
 */
total_count: bigint, 
/**
 * Results per tab (for multi-tab mode). Empty if not using tabs.
 */
tab_results: Array<TabResult>, 
/**
 * Error message if parsing or execution failed.
 */
error: string | null, };
