// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryResultItem } from "./QueryResultItem";

/**
 * Response from running a query.
 */
export type QueryResponse = { 
/**
 * The results matching the query.
 */
results: Array<QueryResultItem>, 
/**
 * Total count of matching items (may be > results.len() if limited).
 */
total_count: bigint, };
