// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuerySort } from "./QuerySort";
import type { QueryViewType } from "./QueryViewType";

/**
 * View configuration for query embed.
 */
export type QueryViewConfig = { 
/**
 * View type (table or list).
 */
view_type: QueryViewType, 
/**
 * Columns to display (for table view). If empty, use defaults.
 */
columns: Array<string>, 
/**
 * Sort configuration.
 */
sort: QuerySort | null, };
