// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortDirection } from "./SortDirection";

/**
 * Sort configuration for query results.
 */
export type QuerySort = { 
/**
 * Property to sort by (e.g., "due_date", "priority", "note_title").
 */
property: string, 
/**
 * Sort direction.
 */
direction: SortDirection, };
