// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardConfig } from "./CardConfig";
import type { InteractiveFilter } from "./InteractiveFilter";
import type { KanbanConfig } from "./KanbanConfig";
import type { QuerySort } from "./QuerySort";
import type { QueryViewType } from "./QueryViewType";
import type { StatsConfig } from "./StatsConfig";

/**
 * View configuration for query embed.
 */
export type QueryViewConfig = { 
/**
 * View type (table, list, kanban, or card).
 */
view_type: QueryViewType, 
/**
 * Columns to display (for table view). If empty, use defaults.
 */
columns: Array<string>, 
/**
 * Sort configuration.
 */
sort: QuerySort | null, 
/**
 * Kanban-specific configuration (only used when view_type is "Kanban").
 */
kanban: KanbanConfig | null, 
/**
 * Card-specific configuration (only used when view_type is "Card").
 */
card: CardConfig | null, 
/**
 * Interactive filter configurations.
 */
interactive_filters: Array<InteractiveFilter> | null, 
/**
 * Stats bar configuration.
 */
stats: StatsConfig | null, };
