// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * View type for displaying query results.
 */
export type QueryViewType = "Table" | "List";
