// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterMatchMode } from "./FilterMatchMode";
import type { PropertyFilter } from "./PropertyFilter";
import type { QueryResultType } from "./QueryResultType";
import type { QueryTab } from "./QueryTab";
import type { QueryViewConfig } from "./QueryViewConfig";

/**
 * A complete query embed definition (parsed from YAML in ```query``` blocks).
 * Supports both single-query mode and multi-tab mode.
 */
export type QueryEmbed = { 
/**
 * Property filters to apply (for single-query mode).
 */
filters: Array<PropertyFilter>, 
/**
 * How to match filters (All = AND, Any = OR). Defaults to All.
 */
match_mode: FilterMatchMode, 
/**
 * What type of results to return. Defaults to Tasks.
 */
result_type: QueryResultType, 
/**
 * Include completed tasks. Defaults to false.
 */
include_completed: boolean, 
/**
 * Maximum number of results. Defaults to 50.
 */
limit: number, 
/**
 * View configuration.
 */
view: QueryViewConfig, 
/**
 * Optional tabs for multi-query mode. If present, overrides single-query fields.
 */
tabs: Array<QueryTab>, };
