// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteListItem } from "./NoteListItem";
import type { PropertyDto } from "./PropertyDto";
import type { TaskWithContext } from "./TaskWithContext";

/**
 * A single query result item (can be a task or a note).
 */
export type QueryResultItem = { 
/**
 * The type of result ("task" or "note").
 */
item_type: string, 
/**
 * Task data (if item_type is "task").
 */
task: TaskWithContext | null, 
/**
 * Note data (if item_type is "note").
 */
note: NoteListItem | null, 
/**
 * Properties of the note (for display in results).
 */
properties: Array<PropertyDto>, };
