// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterMatchMode } from "./FilterMatchMode";
import type { PropertyFilter } from "./PropertyFilter";
import type { QueryResultType } from "./QueryResultType";

/**
 * Request to run a query.
 */
export type QueryRequest = { 
/**
 * Property filters to apply.
 */
filters: Array<PropertyFilter>, 
/**
 * How to match filters (All = AND, Any = OR).
 */
match_mode: FilterMatchMode, 
/**
 * What type of results to return.
 */
result_type: QueryResultType, 
/**
 * Include completed tasks (only for Tasks/Both result types).
 */
include_completed: boolean, 
/**
 * Maximum number of results.
 */
limit: number | null, };
