// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterMatchMode } from "./FilterMatchMode";
import type { PropertyFilter } from "./PropertyFilter";
import type { QueryResultType } from "./QueryResultType";
import type { QueryViewConfig } from "./QueryViewConfig";

/**
 * A single query tab definition.
 */
export type QueryTab = { 
/**
 * Display name for this tab.
 */
name: string, 
/**
 * Property filters to apply for this tab.
 */
filters: Array<PropertyFilter>, 
/**
 * How to match filters (All = AND, Any = OR). Defaults to All.
 */
match_mode: FilterMatchMode, 
/**
 * What type of results to return. Defaults to Tasks.
 */
result_type: QueryResultType, 
/**
 * Include completed tasks. Defaults to false.
 */
include_completed: boolean, 
/**
 * Maximum number of results. Defaults to 50.
 */
limit: number, 
/**
 * View configuration for this tab.
 */
view: QueryViewConfig, };
