// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Entry in the recent vaults list.
 */
export type RecentVault = { path: string, name: string, last_opened: string, };
