// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to rename a property value across all notes with that key.
 */
export type RenamePropertyValueRequest = { 
/**
 * The property key.
 */
key: string, 
/**
 * The current value.
 */
old_value: string, 
/**
 * The new value.
 */
new_value: string, };
