// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to rename a property key across all notes.
 */
export type RenamePropertyKeyRequest = { 
/**
 * The current key name.
 */
old_key: string, 
/**
 * The new key name.
 */
new_key: string, };
