// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to resolve an embed (![[target]] or ![[target#section]]).
 */
export type ResolveEmbedRequest = { 
/**
 * The target note name or path (without .md extension).
 */
target: string, 
/**
 * Optional section slug to extract (e.g., "my-section" from "## My Section").
 */
section: string | null, 
/**
 * Current embedding depth (starts at 0, max 3).
 */
depth: number, };
