// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A search result.
 */
export type SearchResult = { note_id: bigint, path: string, title: string | null, snippet: string | null, score: number, };
