// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to set a folder property value.
 */
export type SetFolderPropertyRequest = { folder_path: string, key: string, value: string | null, property_type: string | null, };
