// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to set a property value.
 */
export type SetPropertyRequest = { note_id: bigint, key: string, value: string | null, property_type: string | null, };
