// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stats bar configuration.
 */
export type StatsConfig = { 
/**
 * Whether to show the stats bar.
 */
show: boolean, 
/**
 * Show total count.
 */
total: boolean, 
/**
 * Property to group stats by (e.g., "read" to show "5 read, 10 unread").
 */
group_by: string | null, };
