// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryResultItem } from "./QueryResultItem";
import type { QueryViewConfig } from "./QueryViewConfig";

/**
 * Results for a single tab.
 */
export type TabResult = { 
/**
 * Tab name.
 */
name: string, 
/**
 * The results for this tab.
 */
results: Array<QueryResultItem>, 
/**
 * Total count of matching items for this tab.
 */
total_count: bigint, 
/**
 * View configuration for this tab.
 */
view: QueryViewConfig, };
