// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertyDto } from "./PropertyDto";
import type { TodoDto } from "./TodoDto";

/**
 * A task (todo) with enriched context from its parent note.
 */
export type TaskWithContext = { 
/**
 * The todo item.
 */
todo: TodoDto, 
/**
 * Path to the note containing this task.
 */
note_path: string, 
/**
 * Title of the note containing this task.
 */
note_title: string | null, 
/**
 * Properties inherited from the parent note (e.g., project, area).
 */
note_properties: Array<PropertyDto>, };
