// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters for filtering tasks.
 */
export type TaskQuery = { 
/**
 * Filter by completion status (None = all, Some(true) = completed, Some(false) = incomplete).
 */
completed: boolean | null, 
/**
 * Filter by context (e.g., "home", "work").
 */
context: string | null, 
/**
 * Filter by priority ("high", "medium", "low").
 */
priority: string | null, 
/**
 * Filter by due date range start (inclusive, YYYY-MM-DD).
 */
due_from: string | null, 
/**
 * Filter by due date range end (inclusive, YYYY-MM-DD).
 */
due_to: string | null, 
/**
 * Filter by note property (key=value).
 */
property_filter: string | null, 
/**
 * Maximum number of results.
 */
limit: number | null, };
