// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Settings for template system (stored in vault config).
 */
export type TemplateSettings = { 
/**
 * Path to the daily note template file (relative to vault root, e.g., "templates/daily.md").
 */
daily_template_path: string | null, 
/**
 * Pattern for daily note file paths (e.g., "journal/{{year}}/{{month}}/{{date}}.md").
 */
daily_note_pattern: string, };
