// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to toggle a todo's completion status.
 */
export type TodoToggleRequest = { todo_id: bigint, completed: boolean, };
