// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update a habit entry.
 */
export type UpdateHabitEntryRequest = { id: bigint, value: string | null, notes: string | null, time: string | null, };
