// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update an existing schedule block.
 */
export type UpdateScheduleBlockRequest = { id: bigint, note_id: bigint | null, date: string | null, start_time: string | null, end_time: string | null, label: string | null, color: string | null, context: string | null, };
