// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HabitType } from "./HabitType";

/**
 * Request to update a habit.
 */
export type UpdateHabitRequest = { id: bigint, name: string | null, description: string | null, habit_type: HabitType | null, unit: string | null, color: string | null, target_value: number | null, archived: boolean | null, sort_order: number | null, };
