// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about an open vault.
 */
export type VaultInfo = { path: string, name: string, note_count: bigint, };
